[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = false

[tasks.build]
workspace = false
command = "cargo"
args = ["build", "${@}"]

[tasks.check-only]
workspace = false
command = "cargo"
args = ["run", "--bin", "check-runner", "${@}"]

[tasks.check]
workspace = false
dependencies = ["build", "check-only"]

[tasks.test-only]
workspace = false
command = "cargo"
args = ["test", "${@}"]

[tasks.test]
workspace = false
dependencies = ["build", "test-only", "check-only"]
