[package]
name = "lpl"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "2.0"
cfg-if = "1.0.0"
smallvec = "1.13.2"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
serde = "1.0.215"
serde_json = "1.0.133"

[[bench]]
name = "json"
harness = false
