[package]
name = "tir-asm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tir-core = { path = "../../core" }
tir-riscv = { path = "../../backends/riscv/" }
tir-backend = { path = "../../backends/common/" }
