[package]
name = "filecheck"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
litcheck-filecheck = "0.2.2"
litcheck-core = "0.2.2"
clap = { version = "4.5.4", features = ["derive"]}
