name: Fuzz

on:
  schedule:
    - cron: '0 0,12 * * *'

env:
  CARGO_TERM_COLOR: always

jobs:
  fuzz:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - core_op_parser
          - riscv_disassembler
      max-parallel: 3
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@nightly
      with:
        components: llvm-tools-preview
    - name: Install cargo-fuzz
      run: cargo install cargo-fuzz
    - name: Fuzz
      run: cargo +nightly fuzz run fuzz_${{ matrix.target }} -- -max_total_time=60 -max_len=16384